version: "3.8"

services:
  node:
    image: kafka-node:latest
    command: init

  kafka1:
    image: kafka-node:latest
    depends_on:
    - node
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - MY_ID=1
      - ALT1_ID=2
      - ALT2_ID=3
