version: "3.8"

services:
  wb1:
    image: kafka-node:latest
    environment:
      - MY_ID=1
      - ALT1_ID=2
      - ALT2_ID=3
      - KAFKA_CLUSTER_ID=xqoDSVREQDK1Qiqa551zwg
  wb2:
    image: kafka-node:latest
    environment:
      - MY_ID=2
      - ALT1_ID=3
      - ALT2_ID=1
      - KAFKA_CLUSTER_ID=xqoDSVREQDK1Qiqa551zwg
  wb3:
    image: kafka-node:latest
    environment:
      - MY_ID=3
      - ALT1_ID=1
      - ALT2_ID=2
      - KAFKA_CLUSTER_ID=xqoDSVREQDK1Qiqa551zwg
